platform :ios, '15.0'

target 'MilkteaCafe' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'MediaPipeTasksText', '0.10.14'

  # Pods for TextEmbedder

end